name: Unit Tests

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'    

jobs:

  build:
    
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          # Alien::MSYS fails to install on windows
          - windows-latest

        perl:
          - '5.22'
          - '5.26'
          - '5.30'
 
        node:
          - '10.x'
          - '13.x'
 
        exclude:
          - os: ubuntu-16.04
            perl: '5.26'
          - os: ubuntu-16.04
            perl: '5.30'
          - os: ubuntu-18.04
            perl: '5.22'
          - os: windows-latest
            perl: '5.22'
          - os: windows-latest
            perl: '5.26'

      fail-fast: false

    name: Node-${{ matrix.node }} & Perl-${{ matrix.perl }} on ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: CPAN Cache
      id: cpan-cache
      uses: actions/cache@v1
      with:
        path: 3rd
        key: ${{ matrix.os }}-cpan-${{ matrix.perl }}-${{ hashFiles('Makefile.PL') }}
        
    - name: Prepare
      run: perl Makefile.PL

    - name: Make 3rd Party
      if: steps.cpan-cache.outputs.cache-hit != 'true'
      run: make thirdparty
      
    - name: Build Automake App
      run: | 
        perl -Ithirdparty/lib/perl5 -Ilib thirdparty/bin/mojo generate automake_app
        cd my-mojolicious-app
        ./configure
        make
        make test
        make dist
    - name: Build Callbackery App
      run: | 
        perl -Ithirdparty/lib/perl5 -Ilib thirdparty/bin/mojo generate callbackery_app
        cd my-callbackery-app
        sudo apt-get install gettext
        ./configure
        make
        make test
        make dist    
